import os.path
import os.path
import shutil
import unittest
from typing import Optional

from photo_lib.new_photo_api import PhotoAPI

"""
File contains two base classes which set up the project directories and test objects.
"""


class ImportTestBaseClass(unittest.TestCase):
    """
    Base Class for all tests in the db_import directory.
    """
    shadow_db: str
    temp_db: str
    media_source: str
    import_source: str
    tbl_dump_dir: str

    api: Optional[PhotoAPI] = None
    tgt_table: Optional[str] = None

    def setUp(self):  # pragma: no cover
        """
        Setup function creates a fresh instance of the db to run the tests against
        """
        # Part of setup is teardown of the test db
        if os.path.exists(self.temp_db):
            shutil.rmtree(self.temp_db)

        shutil.copytree(self.shadow_db, self.temp_db)

        # Part of setup is teardown of the import_source directory
        if os.path.exists(self.import_source):
            shutil.rmtree(self.import_source)

        self.api = PhotoAPI(root_path=self.temp_db,
                            init_loggers=False,
                            init=False)

        self.api.config.batch_size = 10

    def tearDown(self):  # pragma: no cover
        """
        Remove the local instance of the db.
        """
        self.api.cleanup(True)
        self.api = None

        # Part of setup is teardown of the test db
        if os.path.exists(self.temp_db):
            shutil.rmtree(self.temp_db)

        # Part of setup is teardown of the import_source directory
        if os.path.exists(self.import_source):
            shutil.rmtree(self.import_source)


class PrepareDirForImportBaseClass(ImportTestBaseClass):
    """
    Class creates a shadow db that has all tables but is otherwise empty.
    """

    @classmethod
    def setUpClass(cls):  # pragma: no cover
        """
        Function sets the following class attributes:
        - shadow_db: Database Directory which is copied to the test directory prior to running every test.
        - temp_db: Database directory where the tests are performed
        - media_source: Directory where test files generated by generate_dummy_media.py are written
        - import_source: Scratch directory where we put all files to be imported for ease of use

        Prior to running all tests of the class, any previous shadow_db is deleted and a new db created. The new db is
        only initialized. No tables are filled.
        """
        cls.shadow_db = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "shadow_db"))
        cls.temp_db = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "test_db"))
        cls.media_source = os.path.join(os.path.dirname(__file__), "..", "test_file_out")
        cls.import_source = os.path.join(os.path.dirname(__file__), "..", "scratch")
        cls.tbl_dump_dir = os.path.join(os.path.dirname(__file__), "..", "db_dump")
        cls.tgt_table = None

        # Check the input files are present
        if not os.path.exists(os.path.join(os.path.dirname(__file__), "..", "test_file_out")):
            raise FileNotFoundError(
                "Need test files to test the db. Create them with the scripts/generate_dummy_media.py"
            )

        # Check and remove the past of the shadow db
        if os.path.exists(cls.shadow_db):
            shutil.rmtree(cls.shadow_db)

        # Create a fresh instance
        db = PhotoAPI(root_path=cls.shadow_db,
                      init=True,
                      opt_integrity_check=True)

        db.cleanup(fast=True)

    @classmethod
    def tearDownClass(cls):  # pragma: no cover
        """
        Delete the shadow db and unset class attributes:
        - shadow_db
        - temp_db
        - media_source
        - import_source
        - tbl_dump_dir
        """
        path = cls.shadow_db

        shutil.rmtree(path)

        delattr(cls, "tgt_table")
        delattr(cls, "shadow_db")
        delattr(cls, "temp_db")
        delattr(cls, "media_source")
        delattr(cls, "import_source")
        delattr(cls, "tbl_dump_dir")

class PerformImportBaseClass(ImportTestBaseClass):
    """
    Class creates a shadow db that has all tables and has the default db directory imported..
    """
    @classmethod
    def setUpClass(cls):  # pragma: no cover
        """
        Function sets the following class attributes:
        - shadow_db: Database Directory which is copied to the test directory prior to running every test.
        - temp_db: Database directory where the tests are performed
        - media_source: Directory where test files generated by generate_dummy_media.py are written
        - import_source: Scratch directory where we put all files to be imported for ease of use
        - tbl_dump_dir: Directory containing json files of table dumps for testing.

        Prior to running all tests of the class, any previous shadow_db is deleted and a new db created. The new db is
        only initialized. No tables are filled.
        """
        cls.shadow_db = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "shadow_db"))
        cls.temp_db = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "test_db"))
        cls.media_source = os.path.join(os.path.dirname(__file__), "..", "test_file_out")
        cls.import_source = os.path.join(os.path.dirname(__file__), "..", "scratch")
        cls.tbl_dump_dir = os.path.join(os.path.dirname(__file__), "..", "db_dump")

        # Check the input files are present
        if not os.path.exists(os.path.join(os.path.dirname(__file__), "..", "test_file_out")):
            raise FileNotFoundError(
                "Need test files to test the db. Create them with the scripts/generate_dummy_media.py"
            )

        # Check and remove the past of the shadow db
        if os.path.exists(cls.shadow_db):
            shutil.rmtree(cls.shadow_db)

        # Create a fresh instance
        db = PhotoAPI(root_path=cls.shadow_db,
                      init=True,
                      init_loggers=True,
                      opt_integrity_check=True)

        cls.tgt_table = db.prepare_directory_for_import(source_dir=os.path.join(cls.media_source, "db"))

        db.cleanup()

